### PR TITLE
feat: Chat list improvements

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

## Description 

- Changes the chat list as per the dashboard\
- Adds assignee name in chat list if in all assignee filter.

Fixes https://linear.app/chatwoot/issue/CW-14/match-the-design-with-the-dashboard

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have tested in both Android and iOS platform
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranavrajs** [comment]
@iamsivin @muhsin-k Merged this mistakenly, not intended. I was trying to merge the one in the chatwoot repo. Can we please revert this?

**Comment by iamsivin** [comment]
@pranavrajs, Can you check this PR? It doesn't have any breaking changes. If it's okay, we do not need to revert this PR. If there is any suggestion, I can raise another PR.

**Comment by muhsin-k** [comment]
@iamsivin I will check these changes and let you know.

**Comment by muhsin-k** [comment]
There is one issue while selecting labels from the conversation. I will add the fix in a separate PR.

**Pull request merged**
