### PR TITLE
Feature: add automated end-to-end testing using detox

### PR DESCRIPTION
**Pull request by arufanov**
@muhsin-k here is pull requests for #30 PR contain setup for iOS with single simple tests. There are some issues about PR:
* [ ] tests are not included in CI.
* [x] which ios configuration should be tested: debug or release? Now is debug, it is discussable. 
* [ ] I haven't test with android, should I?
* [x] e2e dir excluded from eslint check. Looks like not OK, and should be fixed. What do you thing? 
* [x] simulator should be run before run tests. It is looks like bug, I am researching. 

Any feedback is welcome.

### CODE REVIEW

**Comment by muhsin-k** [comment]
@arufanov Thank you for this fantastic PR 
_I haven't test with android, should I?_
**Is there any challenges that are blocking android?**
_E2E dir excluded from eslint check. Looks like not OK, and should be fixed. What do you thing?_
**It is okay**
The PR looks good to me. Is it possible to share the working screencast?

**Comment by arufanov** [comment]
> @arufanov Thank you for this fantastic PR.
> _I haven't test with android, should I?_
> **Is there any challenges that are blocking android?**
No, there isn't any blocking issue, I will check later. 

> _E2E dir excluded from eslint check. Looks like not OK, and should be fixed. What do you thing?_
> **It is okay**
This issue have been fixed.

> The PR looks good to me. Is it possible to share the working screencast?

Sure, I have attached screencast. [Screen Recording 2020-09-10 at 14.21.17.mov.zip](https://github.com/chatwoot/chatwoot-mobile-app/files/5201259/Screen.Recording.2020-09-10.at.14.21.17.mov.zip)  Pay attention: simulator should be pre run (need extra step in ci), otherwise error will occurs. I will try to understand is it ok on "hello world" example. After it I remove WIP (=work in progress) value. Let me know if it is not essential for you. 

P.S.
I would be great if you add me to project with rights to create a branch and PR. It allow me to avoid fork repo on every PR.  Thanks!

**Comment by arufanov** [comment]
@muhsin-k 
* fixed "simulator should be run before run tests. It is looks like bug, I am researching." It was my problem, fixed by erasing all simulators. 

I suppose PR is ready, any feedback is welcome! Otherwise would be great to see it develop branch.

**Comment by muhsin-k** [comment]
@arufanov I will merge the PR once I test it out in my local machine.

**Comment by muhsin-k** [comment]
> P.S.
> I would be great if you add me to project with rights to create a branch and PR. It allow me to avoid fork repo on every PR. Thanks!

@arufanov We have added you as a contributor 🙂. All types of contributions are welcome.

**Pull request merged**
