### PR TITLE
chore: Contact details view

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

## Description 

- Updated icons in the conversation details screen
- Updated styles to support the v2 theme
- Minor UI improvements
- Updated User avatar in this component
- Clean up styles
- Uses the latest component, Header, Text, Icons, Pressable

### CODE REVIEW

**Comment by muhsin-k** [comment]
@iamsivin Please fix the conflicts.

**Comment by iamsivin** [comment]
> @iamsivin Please fix the conflicts.

Done

**Comment by muhsin-k** [comment]
@iamsivin Anything is pending here?

**Comment by iamsivin** [comment]
> @iamsivin Anything is pending here?

I think it's good to go.

**Review by muhsin-k — APPROVED** [review]

**Pull request merged**
